### ISSUE TITLE
Assignment 3 - Javascript Refresh!

### ISSUE THREAD

**Issue by lizthrilla** [BreeJax/ReactAssignmentsSDG#3]
# Wax On, Wax Off

> A **koan** is a riddle or puzzle that Zen Buddhists use during meditation to help them unravel greater truths about the world and about themselves. Zen masters have been testing their students with these stories, questions, or phrases for centuries.

As we learn a new language, we need to practice the new ideas, syntax, and paradigms that come what that language. The idea of language Koans helps both beginners and veterans learn the ins and outs of the language.

## Objectives

- Work on the Koans to practice using JavaScript

### Explorer Mode

- [x] Complete the [Koans](https://github.com/suncoast-devs/koans)

### Adventure Mode
- [ ] Clean up Score Board
- [x] Do level 8 KYU in Javascript Kata on Code Wars

### Epic Mode:
- [x] Do a level up Code Kata in Code Wars

**Comment by BreeJax** [comment]
https://github.com/BreeJax/koans-1

**Comment by BreeJax** [comment]
https://github.com/BreeJax/codeWars/tree/master

**Comment by lizthrilla** [comment]
Your homework was marked: **Exceeds Expectations**

![Shake it cus you made it!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f8192466340c451ea46a1b17477b92f5f01a8ba7/danding%20pup.gif)
> &ldquo;Shake it cus you made it!&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/19)**__
